// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/chainwatch/v1/chainwatch.proto

package chainwatchv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChainwatchService_Evaluate_FullMethodName    = "/chainwatch.v1.ChainwatchService/Evaluate"
	ChainwatchService_Approve_FullMethodName     = "/chainwatch.v1.ChainwatchService/Approve"
	ChainwatchService_Deny_FullMethodName        = "/chainwatch.v1.ChainwatchService/Deny"
	ChainwatchService_ListPending_FullMethodName = "/chainwatch.v1.ChainwatchService/ListPending"
)

// ChainwatchServiceClient is the client API for ChainwatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChainwatchServiceClient interface {
	Evaluate(ctx context.Context, in *EvalRequest, opts ...grpc.CallOption) (*EvalResponse, error)
	Approve(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*ApproveResponse, error)
	Deny(ctx context.Context, in *DenyRequest, opts ...grpc.CallOption) (*DenyResponse, error)
	ListPending(ctx context.Context, in *ListPendingRequest, opts ...grpc.CallOption) (*ListPendingResponse, error)
}

type chainwatchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChainwatchServiceClient(cc grpc.ClientConnInterface) ChainwatchServiceClient {
	return &chainwatchServiceClient{cc}
}

func (c *chainwatchServiceClient) Evaluate(ctx context.Context, in *EvalRequest, opts ...grpc.CallOption) (*EvalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvalResponse)
	err := c.cc.Invoke(ctx, ChainwatchService_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainwatchServiceClient) Approve(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*ApproveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveResponse)
	err := c.cc.Invoke(ctx, ChainwatchService_Approve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainwatchServiceClient) Deny(ctx context.Context, in *DenyRequest, opts ...grpc.CallOption) (*DenyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DenyResponse)
	err := c.cc.Invoke(ctx, ChainwatchService_Deny_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainwatchServiceClient) ListPending(ctx context.Context, in *ListPendingRequest, opts ...grpc.CallOption) (*ListPendingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingResponse)
	err := c.cc.Invoke(ctx, ChainwatchService_ListPending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainwatchServiceServer is the server API for ChainwatchService service.
// All implementations must embed UnimplementedChainwatchServiceServer
// for forward compatibility.
type ChainwatchServiceServer interface {
	Evaluate(context.Context, *EvalRequest) (*EvalResponse, error)
	Approve(context.Context, *ApproveRequest) (*ApproveResponse, error)
	Deny(context.Context, *DenyRequest) (*DenyResponse, error)
	ListPending(context.Context, *ListPendingRequest) (*ListPendingResponse, error)
	mustEmbedUnimplementedChainwatchServiceServer()
}

// UnimplementedChainwatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChainwatchServiceServer struct{}

func (UnimplementedChainwatchServiceServer) Evaluate(context.Context, *EvalRequest) (*EvalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedChainwatchServiceServer) Approve(context.Context, *ApproveRequest) (*ApproveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Approve not implemented")
}
func (UnimplementedChainwatchServiceServer) Deny(context.Context, *DenyRequest) (*DenyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deny not implemented")
}
func (UnimplementedChainwatchServiceServer) ListPending(context.Context, *ListPendingRequest) (*ListPendingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPending not implemented")
}
func (UnimplementedChainwatchServiceServer) mustEmbedUnimplementedChainwatchServiceServer() {}
func (UnimplementedChainwatchServiceServer) testEmbeddedByValue()                           {}

// UnsafeChainwatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainwatchServiceServer will
// result in compilation errors.
type UnsafeChainwatchServiceServer interface {
	mustEmbedUnimplementedChainwatchServiceServer()
}

func RegisterChainwatchServiceServer(s grpc.ServiceRegistrar, srv ChainwatchServiceServer) {
	// If the following call panics, it indicates UnimplementedChainwatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChainwatchService_ServiceDesc, srv)
}

func _ChainwatchService_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainwatchServiceServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainwatchService_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainwatchServiceServer).Evaluate(ctx, req.(*EvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainwatchService_Approve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainwatchServiceServer).Approve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainwatchService_Approve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainwatchServiceServer).Approve(ctx, req.(*ApproveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainwatchService_Deny_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DenyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainwatchServiceServer).Deny(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainwatchService_Deny_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainwatchServiceServer).Deny(ctx, req.(*DenyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainwatchService_ListPending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainwatchServiceServer).ListPending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainwatchService_ListPending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainwatchServiceServer).ListPending(ctx, req.(*ListPendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChainwatchService_ServiceDesc is the grpc.ServiceDesc for ChainwatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChainwatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainwatch.v1.ChainwatchService",
	HandlerType: (*ChainwatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _ChainwatchService_Evaluate_Handler,
		},
		{
			MethodName: "Approve",
			Handler:    _ChainwatchService_Approve_Handler,
		},
		{
			MethodName: "Deny",
			Handler:    _ChainwatchService_Deny_Handler,
		},
		{
			MethodName: "ListPending",
			Handler:    _ChainwatchService_ListPending_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/chainwatch/v1/chainwatch.proto",
}
