// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/chainwatch/v1/chainwatch.proto

package chainwatchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          string                 `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Params        map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Meta          map[string]string      `protobuf:"bytes,5,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_api_proto_chainwatch_v1_chainwatch_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *Action) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Action) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Action) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Action) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type EvalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        *Action                `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Purpose       string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalRequest) Reset() {
	*x = EvalRequest{}
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalRequest) ProtoMessage() {}

func (x *EvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalRequest.ProtoReflect.Descriptor instead.
func (*EvalRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chainwatch_v1_chainwatch_proto_rawDescGZIP(), []int{1}
}

func (x *EvalRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *EvalRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *EvalRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type EvalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      string                 `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Tier          int32                  `protobuf:"varint,3,opt,name=tier,proto3" json:"tier,omitempty"`
	PolicyId      string                 `protobuf:"bytes,4,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	ApprovalKey   string                 `protobuf:"bytes,5,opt,name=approval_key,json=approvalKey,proto3" json:"approval_key,omitempty"`
	TraceId       string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalResponse) Reset() {
	*x = EvalResponse{}
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalResponse) ProtoMessage() {}

func (x *EvalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalResponse.ProtoReflect.Descriptor instead.
func (*EvalResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chainwatch_v1_chainwatch_proto_rawDescGZIP(), []int{2}
}

func (x *EvalResponse) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *EvalResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EvalResponse) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *EvalResponse) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *EvalResponse) GetApprovalKey() string {
	if x != nil {
		return x.ApprovalKey
	}
	return ""
}

func (x *EvalResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type ApproveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Duration      string                 `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequest) Reset() {
	*x = ApproveRequest{}
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequest) ProtoMessage() {}

func (x *ApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chainwatch_v1_chainwatch_proto_rawDescGZIP(), []int{3}
}

func (x *ApproveRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ApproveRequest) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

type ApproveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveResponse) Reset() {
	*x = ApproveResponse{}
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveResponse) ProtoMessage() {}

func (x *ApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveResponse.ProtoReflect.Descriptor instead.
func (*ApproveResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chainwatch_v1_chainwatch_proto_rawDescGZIP(), []int{4}
}

func (x *ApproveResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ApproveResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DenyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyRequest) Reset() {
	*x = DenyRequest{}
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyRequest) ProtoMessage() {}

func (x *DenyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyRequest.ProtoReflect.Descriptor instead.
func (*DenyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chainwatch_v1_chainwatch_proto_rawDescGZIP(), []int{5}
}

func (x *DenyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DenyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyResponse) Reset() {
	*x = DenyResponse{}
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyResponse) ProtoMessage() {}

func (x *DenyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyResponse.ProtoReflect.Descriptor instead.
func (*DenyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chainwatch_v1_chainwatch_proto_rawDescGZIP(), []int{6}
}

func (x *DenyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DenyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListPendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingRequest) Reset() {
	*x = ListPendingRequest{}
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingRequest) ProtoMessage() {}

func (x *ListPendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingRequest.ProtoReflect.Descriptor instead.
func (*ListPendingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chainwatch_v1_chainwatch_proto_rawDescGZIP(), []int{7}
}

type PendingApproval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingApproval) Reset() {
	*x = PendingApproval{}
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingApproval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingApproval) ProtoMessage() {}

func (x *PendingApproval) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingApproval.ProtoReflect.Descriptor instead.
func (*PendingApproval) Descriptor() ([]byte, []int) {
	return file_api_proto_chainwatch_v1_chainwatch_proto_rawDescGZIP(), []int{8}
}

func (x *PendingApproval) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PendingApproval) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PendingApproval) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PendingApproval) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PendingApproval) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListPendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approvals     []*PendingApproval     `protobuf:"bytes,1,rep,name=approvals,proto3" json:"approvals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingResponse) Reset() {
	*x = ListPendingResponse{}
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingResponse) ProtoMessage() {}

func (x *ListPendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingResponse.ProtoReflect.Descriptor instead.
func (*ListPendingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chainwatch_v1_chainwatch_proto_rawDescGZIP(), []int{9}
}

func (x *ListPendingResponse) GetApprovals() []*PendingApproval {
	if x != nil {
		return x.Approvals
	}
	return nil
}

var File_api_proto_chainwatch_v1_chainwatch_proto protoreflect.FileDescriptor

const file_api_proto_chainwatch_v1_chainwatch_proto_rawDesc = "" +
	"\n" +
	"(api/proto/chainwatch/v1/chainwatch.proto\x12\rchainwatch.v1\"\xba\x02\n" +
	"\x06Action\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x129\n" +
	"\x06params\x18\x04 \x03(\v2!.chainwatch.v1.Action.ParamsEntryR\x06params\x123\n" +
	"\x04meta\x18\x05 \x03(\v2\x1f.chainwatch.v1.Action.MetaEntryR\x04meta\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\vEvalRequest\x12-\n" +
	"\x06action\x18\x01 \x01(\v2\x15.chainwatch.v1.ActionR\x06action\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\"\xb1\x01\n" +
	"\fEvalResponse\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\tR\bdecision\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x12\n" +
	"\x04tier\x18\x03 \x01(\x05R\x04tier\x12\x1b\n" +
	"\tpolicy_id\x18\x04 \x01(\tR\bpolicyId\x12!\n" +
	"\fapproval_key\x18\x05 \x01(\tR\vapprovalKey\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\">\n" +
	"\x0eApproveRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\tR\bduration\";\n" +
	"\x0fApproveResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x1f\n" +
	"\vDenyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"8\n" +
	"\fDenyResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x14\n" +
	"\x12ListPendingRequest\"\x8e\x01\n" +
	"\x0fPendingApproval\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"S\n" +
	"\x13ListPendingResponse\x12<\n" +
	"\tapprovals\x18\x01 \x03(\v2\x1e.chainwatch.v1.PendingApprovalR\tapprovals2\xb9\x02\n" +
	"\x11ChainwatchService\x12C\n" +
	"\bEvaluate\x12\x1a.chainwatch.v1.EvalRequest\x1a\x1b.chainwatch.v1.EvalResponse\x12H\n" +
	"\aApprove\x12\x1d.chainwatch.v1.ApproveRequest\x1a\x1e.chainwatch.v1.ApproveResponse\x12?\n" +
	"\x04Deny\x12\x1a.chainwatch.v1.DenyRequest\x1a\x1b.chainwatch.v1.DenyResponse\x12T\n" +
	"\vListPending\x12!.chainwatch.v1.ListPendingRequest\x1a\".chainwatch.v1.ListPendingResponseBEZCgithub.com/ppiankov/chainwatch/api/proto/chainwatch/v1;chainwatchv1b\x06proto3"

var (
	file_api_proto_chainwatch_v1_chainwatch_proto_rawDescOnce sync.Once
	file_api_proto_chainwatch_v1_chainwatch_proto_rawDescData []byte
)

func file_api_proto_chainwatch_v1_chainwatch_proto_rawDescGZIP() []byte {
	file_api_proto_chainwatch_v1_chainwatch_proto_rawDescOnce.Do(func() {
		file_api_proto_chainwatch_v1_chainwatch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_chainwatch_v1_chainwatch_proto_rawDesc), len(file_api_proto_chainwatch_v1_chainwatch_proto_rawDesc)))
	})
	return file_api_proto_chainwatch_v1_chainwatch_proto_rawDescData
}

var file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_chainwatch_v1_chainwatch_proto_goTypes = []any{
	(*Action)(nil),              // 0: chainwatch.v1.Action
	(*EvalRequest)(nil),         // 1: chainwatch.v1.EvalRequest
	(*EvalResponse)(nil),        // 2: chainwatch.v1.EvalResponse
	(*ApproveRequest)(nil),      // 3: chainwatch.v1.ApproveRequest
	(*ApproveResponse)(nil),     // 4: chainwatch.v1.ApproveResponse
	(*DenyRequest)(nil),         // 5: chainwatch.v1.DenyRequest
	(*DenyResponse)(nil),        // 6: chainwatch.v1.DenyResponse
	(*ListPendingRequest)(nil),  // 7: chainwatch.v1.ListPendingRequest
	(*PendingApproval)(nil),     // 8: chainwatch.v1.PendingApproval
	(*ListPendingResponse)(nil), // 9: chainwatch.v1.ListPendingResponse
	nil,                         // 10: chainwatch.v1.Action.ParamsEntry
	nil,                         // 11: chainwatch.v1.Action.MetaEntry
}
var file_api_proto_chainwatch_v1_chainwatch_proto_depIdxs = []int32{
	10, // 0: chainwatch.v1.Action.params:type_name -> chainwatch.v1.Action.ParamsEntry
	11, // 1: chainwatch.v1.Action.meta:type_name -> chainwatch.v1.Action.MetaEntry
	0,  // 2: chainwatch.v1.EvalRequest.action:type_name -> chainwatch.v1.Action
	8,  // 3: chainwatch.v1.ListPendingResponse.approvals:type_name -> chainwatch.v1.PendingApproval
	1,  // 4: chainwatch.v1.ChainwatchService.Evaluate:input_type -> chainwatch.v1.EvalRequest
	3,  // 5: chainwatch.v1.ChainwatchService.Approve:input_type -> chainwatch.v1.ApproveRequest
	5,  // 6: chainwatch.v1.ChainwatchService.Deny:input_type -> chainwatch.v1.DenyRequest
	7,  // 7: chainwatch.v1.ChainwatchService.ListPending:input_type -> chainwatch.v1.ListPendingRequest
	2,  // 8: chainwatch.v1.ChainwatchService.Evaluate:output_type -> chainwatch.v1.EvalResponse
	4,  // 9: chainwatch.v1.ChainwatchService.Approve:output_type -> chainwatch.v1.ApproveResponse
	6,  // 10: chainwatch.v1.ChainwatchService.Deny:output_type -> chainwatch.v1.DenyResponse
	9,  // 11: chainwatch.v1.ChainwatchService.ListPending:output_type -> chainwatch.v1.ListPendingResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_chainwatch_v1_chainwatch_proto_init() }
func file_api_proto_chainwatch_v1_chainwatch_proto_init() {
	if File_api_proto_chainwatch_v1_chainwatch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_chainwatch_v1_chainwatch_proto_rawDesc), len(file_api_proto_chainwatch_v1_chainwatch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_chainwatch_v1_chainwatch_proto_goTypes,
		DependencyIndexes: file_api_proto_chainwatch_v1_chainwatch_proto_depIdxs,
		MessageInfos:      file_api_proto_chainwatch_v1_chainwatch_proto_msgTypes,
	}.Build()
	File_api_proto_chainwatch_v1_chainwatch_proto = out.File
	file_api_proto_chainwatch_v1_chainwatch_proto_goTypes = nil
	file_api_proto_chainwatch_v1_chainwatch_proto_depIdxs = nil
}
