package macprofile

import (
	"fmt"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/ppiankov/chainwatch/internal/denylist"
	"github.com/ppiankov/chainwatch/internal/profile"
)

const (
	defaultAppArmorName = "chainwatch-agent"
	defaultSELinuxName  = "chainwatch_agent"
)

var (
	appArmorNameSanitizer = regexp.MustCompile(`[^a-zA-Z0-9_-]+`)
	selinuxNameSanitizer  = regexp.MustCompile(`[^a-z0-9_]+`)
	tokenSanitizer        = regexp.MustCompile(`[^a-zA-Z0-9_./+-]`)
	allCapsToken          = regexp.MustCompile(`^[A-Z0-9_]+$`)
	commandSplitter       = regexp.MustCompile(`\|\||&&|[|;]`)
)

// Restrictions is the effective denylist surface after profile merge.
type Restrictions struct {
	ProfileName     string
	URLPatterns     []string
	FilePatterns    []string
	CommandPatterns []string
}

// LoadRestrictions loads denylist + profile boundaries into a single effective view.
func LoadRestrictions(profileName, denylistPath string) (*Restrictions, error) {
	if strings.TrimSpace(profileName) == "" {
		return nil, fmt.Errorf("profile name is required")
	}

	p, err := profile.Load(profileName)
	if err != nil {
		return nil, fmt.Errorf("load profile %q: %w", profileName, err)
	}

	dl, err := denylist.Load(denylistPath)
	if err != nil {
		return nil, fmt.Errorf("load denylist: %w", err)
	}

	profile.ApplyToDenylist(p, dl)
	raw := dl.ToMap()

	return &Restrictions{
		ProfileName:     profileName,
		URLPatterns:     sortedUnique(toStringSlice(raw["urls"])),
		FilePatterns:    sortedUnique(toStringSlice(raw["files"])),
		CommandPatterns: sortedUnique(toStringSlice(raw["commands"])),
	}, nil
}

// GenerateAppArmor renders an AppArmor profile from effective restrictions.
func GenerateAppArmor(profileName string, r *Restrictions) (string, error) {
	if r == nil {
		return "", fmt.Errorf("restrictions are required")
	}

	aaName := sanitizeAppArmorProfileName(profileName)
	fileRules := appArmorFileRules(r.FilePatterns)
	execRules := appArmorExecRules(r.CommandPatterns)
	hasNetworkRestrictions := len(r.URLPatterns) > 0

	var b strings.Builder
	b.WriteString("# Generated by chainwatch generate-apparmor\n")
	b.WriteString(fmt.Sprintf("# Source profile: %s\n", r.ProfileName))
	b.WriteString("# Restrictions are translated from chainwatch denylist semantics.\n")
	b.WriteString("# URL denylist rules are mapped to coarse outbound socket restrictions.\n")
	b.WriteString("#include <tunables/global>\n\n")
	b.WriteString(fmt.Sprintf("profile %s flags=(attach_disconnected,mediate_deleted) {\n", aaName))
	b.WriteString("  #include <abstractions/base>\n\n")

	if len(fileRules) > 0 {
		b.WriteString("  # File restrictions from denylist.files\n")
		for _, rule := range fileRules {
			b.WriteString(fmt.Sprintf("  deny %s rwklx,\n", rule))
		}
		b.WriteString("\n")
	}

	if len(execRules) > 0 {
		b.WriteString("  # Execute restrictions from denylist.commands\n")
		for _, rule := range execRules {
			b.WriteString(fmt.Sprintf("  deny %s x,\n", rule))
		}
		b.WriteString("\n")
	}

	if hasNetworkRestrictions {
		b.WriteString("  # URL restrictions from denylist.urls (coarse egress mapping)\n")
		b.WriteString("  deny network inet stream,\n")
		b.WriteString("  deny network inet dgram,\n")
		b.WriteString("  deny network inet6 stream,\n")
		b.WriteString("  deny network inet6 dgram,\n\n")
	}

	b.WriteString("}\n")
	return b.String(), nil
}

// GenerateSELinux renders a SELinux type-enforcement module from effective restrictions.
func GenerateSELinux(moduleName string, r *Restrictions) (string, error) {
	if r == nil {
		return "", fmt.Errorf("restrictions are required")
	}

	mod := sanitizeSELinuxModuleName(moduleName)
	agentType := mod + "_agent_t"
	blockedFileType := mod + "_blocked_file_t"
	blockedExecType := mod + "_blocked_exec_t"
	fileRegexes := selinuxFileRegexes(r.FilePatterns)
	execRegexes := selinuxExecRegexes(r.CommandPatterns)
	hasNetworkRestrictions := len(r.URLPatterns) > 0

	var b strings.Builder
	b.WriteString("# Generated by chainwatch generate-selinux\n")
	b.WriteString(fmt.Sprintf("# Source profile: %s\n", r.ProfileName))
	b.WriteString("# Compile: checkmodule -M -m -o ")
	b.WriteString(mod)
	b.WriteString(".mod <this-file>.te\n")
	b.WriteString("# Package: semodule_package -o ")
	b.WriteString(mod)
	b.WriteString(".pp -m ")
	b.WriteString(mod)
	b.WriteString(".mod\n\n")
	b.WriteString(fmt.Sprintf("module %s 1.0;\n\n", mod))
	b.WriteString("require {\n")
	b.WriteString("    class dir { add_name getattr open read remove_name reparent search write };\n")
	b.WriteString("    class file { append create entrypoint execute execute_no_trans getattr ioctl link lock map open read rename setattr unlink write };\n")
	if hasNetworkRestrictions {
		b.WriteString("    class tcp_socket name_connect;\n")
		b.WriteString("    class udp_socket name_connect;\n")
	}
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("type %s;\n", agentType))
	if len(fileRegexes) > 0 {
		b.WriteString(fmt.Sprintf("type %s;\n", blockedFileType))
	}
	if len(execRegexes) > 0 {
		b.WriteString(fmt.Sprintf("type %s;\n", blockedExecType))
	}
	b.WriteString("\n")

	if len(fileRegexes) > 0 {
		b.WriteString("# Block access to files labeled as chainwatch denied paths.\n")
		b.WriteString(fmt.Sprintf("neverallow %s %s:file { append create entrypoint execute execute_no_trans getattr ioctl link lock map open read rename setattr unlink write };\n", agentType, blockedFileType))
		b.WriteString(fmt.Sprintf("neverallow %s %s:dir { add_name getattr open read remove_name reparent search write };\n\n", agentType, blockedFileType))
	}

	if len(execRegexes) > 0 {
		b.WriteString("# Block execute of binaries labeled as chainwatch denied commands.\n")
		b.WriteString(fmt.Sprintf("neverallow %s %s:file { entrypoint execute execute_no_trans getattr map open read };\n\n", agentType, blockedExecType))
	}

	if hasNetworkRestrictions {
		b.WriteString("# URL denylist mapped to coarse egress restriction.\n")
		b.WriteString(fmt.Sprintf("neverallow %s self:tcp_socket name_connect;\n", agentType))
		b.WriteString(fmt.Sprintf("neverallow %s self:udp_socket name_connect;\n\n", agentType))
	}

	if len(fileRegexes) > 0 || len(execRegexes) > 0 {
		b.WriteString("# Labeling guidance (run as root):\n")
		for _, rx := range fileRegexes {
			b.WriteString(fmt.Sprintf("# semanage fcontext -a -t %s '%s'\n", blockedFileType, rx))
		}
		for _, rx := range execRegexes {
			b.WriteString(fmt.Sprintf("# semanage fcontext -a -t %s '%s'\n", blockedExecType, rx))
		}
		b.WriteString("# restorecon -Rv <path>\n")
	}

	return b.String(), nil
}

func toStringSlice(v any) []string {
	switch typed := v.(type) {
	case []string:
		return append([]string(nil), typed...)
	case []any:
		out := make([]string, 0, len(typed))
		for _, item := range typed {
			s, ok := item.(string)
			if !ok {
				continue
			}
			s = strings.TrimSpace(s)
			if s == "" {
				continue
			}
			out = append(out, s)
		}
		return out
	default:
		return nil
	}
}

func appArmorFileRules(patterns []string) []string {
	var rules []string
	for _, pattern := range patterns {
		rules = append(rules, filePatternToAppArmorGlobs(pattern)...)
	}
	return sortedUnique(rules)
}

func appArmorExecRules(patterns []string) []string {
	var rules []string
	for _, pattern := range patterns {
		for _, cmd := range extractExecutables(pattern) {
			rules = append(rules, commandToAppArmorExecGlobs(cmd)...)
		}
	}
	return sortedUnique(rules)
}

func filePatternToAppArmorGlobs(pattern string) []string {
	normalized := strings.TrimSpace(strings.ReplaceAll(pattern, "\\", "/"))
	if normalized == "" {
		return nil
	}

	var out []string
	switch {
	case strings.HasPrefix(normalized, "~/"):
		suffix := strings.TrimPrefix(normalized, "~/")
		out = append(out, "@{HOME}/"+suffix)
		out = append(out, "/**/"+suffix)
	case strings.HasPrefix(normalized, "/"):
		out = append(out, normalized)
	case strings.HasPrefix(normalized, "**/"):
		out = append(out, "/**/"+strings.TrimPrefix(normalized, "**/"))
	default:
		out = append(out, "/**/"+strings.TrimPrefix(normalized, "./"))
	}

	return sortedUnique(out)
}

func extractExecutables(pattern string) []string {
	normalized := strings.TrimSpace(pattern)
	if normalized == "" {
		return nil
	}

	segments := commandSplitter.Split(normalized, -1)
	var out []string
	for _, segment := range segments {
		fields := strings.Fields(strings.TrimSpace(segment))
		if len(fields) == 0 {
			continue
		}

		candidate := cleanToken(fields[0])
		if !isExecutableToken(candidate) {
			continue
		}
		out = append(out, candidate)

		// Handle forms like "sudo su" so both binaries are denied.
		if candidate == "sudo" && len(fields) > 1 {
			next := cleanToken(fields[1])
			if isExecutableToken(next) {
				out = append(out, next)
			}
		}
	}

	return sortedUnique(out)
}

func cleanToken(token string) string {
	token = strings.TrimSpace(token)
	token = strings.Trim(token, "\"'`()")
	token = strings.TrimRight(token, ",")
	token = strings.TrimSpace(token)
	if strings.HasSuffix(token, ".") {
		token = strings.TrimSuffix(token, ".")
	}
	return token
}

func isExecutableToken(token string) bool {
	if token == "" {
		return false
	}
	if token == ">" || token == "<" || token == "<<" || token == ">>" {
		return false
	}
	if strings.HasPrefix(token, "-") {
		return false
	}
	if strings.Contains(token, "=") && !strings.HasPrefix(token, "/") {
		return false
	}
	if strings.HasPrefix(token, "/proc/") {
		return false
	}
	if allCapsToken.MatchString(token) {
		return false
	}
	if tokenSanitizer.MatchString(token) {
		return false
	}
	base := filepath.Base(token)
	switch base {
	case "export", "declare", "compgen":
		return false
	}
	return true
}

func commandToAppArmorExecGlobs(command string) []string {
	command = strings.TrimSpace(command)
	if command == "" {
		return nil
	}

	if strings.HasPrefix(command, "/") {
		return []string{command}
	}

	dirs := []string{
		"/bin/",
		"/usr/bin/",
		"/sbin/",
		"/usr/sbin/",
		"/usr/local/bin/",
	}
	out := make([]string, 0, len(dirs))
	for _, dir := range dirs {
		out = append(out, dir+command)
	}
	return out
}

func selinuxFileRegexes(patterns []string) []string {
	var out []string
	for _, pattern := range patterns {
		out = append(out, filePatternToSELinuxRegexes(pattern)...)
	}
	return sortedUnique(out)
}

func selinuxExecRegexes(patterns []string) []string {
	var out []string
	for _, pattern := range patterns {
		for _, cmd := range extractExecutables(pattern) {
			out = append(out, commandToSELinuxRegexes(cmd)...)
		}
	}
	return sortedUnique(out)
}

func filePatternToSELinuxRegexes(pattern string) []string {
	normalized := strings.TrimSpace(strings.ReplaceAll(pattern, "\\", "/"))
	if normalized == "" {
		return nil
	}

	var out []string
	switch {
	case strings.HasPrefix(normalized, "~/"):
		suffix := strings.TrimPrefix(normalized, "~/")
		out = append(out, "/home/[^/]+/"+globToSELinuxRegex(suffix))
		out = append(out, "/root/"+globToSELinuxRegex(suffix))
	case strings.HasPrefix(normalized, "/"):
		out = append(out, globToSELinuxRegex(normalized))
	case strings.HasPrefix(normalized, "**/"):
		out = append(out, "/.*/"+globToSELinuxRegex(strings.TrimPrefix(normalized, "**/")))
	default:
		out = append(out, "/.*/"+globToSELinuxRegex(strings.TrimPrefix(normalized, "./")))
	}

	return sortedUnique(out)
}

func commandToSELinuxRegexes(command string) []string {
	command = strings.TrimSpace(command)
	if command == "" {
		return nil
	}

	if strings.HasPrefix(command, "/") {
		return []string{regexp.QuoteMeta(command)}
	}

	quoted := regexp.QuoteMeta(command)
	dirs := []string{
		"/bin/",
		"/usr/bin/",
		"/sbin/",
		"/usr/sbin/",
		"/usr/local/bin/",
	}
	out := make([]string, 0, len(dirs))
	for _, dir := range dirs {
		out = append(out, dir+quoted)
	}
	return out
}

func globToSELinuxRegex(pattern string) string {
	var b strings.Builder
	for i := 0; i < len(pattern); i++ {
		ch := pattern[i]
		if ch == '*' {
			if i+1 < len(pattern) && pattern[i+1] == '*' {
				b.WriteString(".*")
				i++
				continue
			}
			b.WriteString("[^/]*")
			continue
		}

		switch ch {
		case '.', '+', '?', '^', '$', '(', ')', '[', ']', '{', '}', '|':
			b.WriteByte('\\')
		}
		b.WriteByte(ch)
	}
	return b.String()
}

func sanitizeAppArmorProfileName(name string) string {
	name = strings.TrimSpace(name)
	if name == "" {
		return defaultAppArmorName
	}
	name = appArmorNameSanitizer.ReplaceAllString(name, "-")
	name = strings.Trim(name, "-_")
	if name == "" {
		return defaultAppArmorName
	}
	return name
}

func sanitizeSELinuxModuleName(name string) string {
	name = strings.ToLower(strings.TrimSpace(name))
	name = selinuxNameSanitizer.ReplaceAllString(name, "_")
	name = strings.Trim(name, "_")
	if name == "" {
		name = defaultSELinuxName
	}
	if name[0] >= '0' && name[0] <= '9' {
		name = "cw_" + name
	}
	return name
}

func sortedUnique(values []string) []string {
	seen := make(map[string]struct{}, len(values))
	out := make([]string, 0, len(values))
	for _, value := range values {
		normalized := strings.TrimSpace(value)
		if normalized == "" {
			continue
		}
		if _, ok := seen[normalized]; ok {
			continue
		}
		seen[normalized] = struct{}{}
		out = append(out, normalized)
	}
	sort.Strings(out)
	return out
}
